name: Patch YouTube ReVanced

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: "URL to download YouTube APK"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run update_links.sh script
      - name: Update Links
        run: |
          chmod +x scripts/update_links.sh
          ./scripts/update_links.sh

      # Source updated environment variables
      - name: Source Updated URLs
        run: source .env

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Download ReVanced CLI
      - name: Download ReVanced CLI
        run: |
          wget $CLI_URL -O revanced-cli.jar

      # Download Patches and Integrations
      - name: Download Patches and Integrations
        run: |
          wget $PATCHES_URL -O revanced-patches.jar
          wget $INTEGRATION_URL -O integrations.apk

      # Download YouTube APK
      - name: Download YouTube APK
        run: |
          wget ${{ github.event.inputs.apk_url || env.YOUTUBE_URL }} -O youtube.apk

      # Patch YouTube APK
      - name: Patch YouTube
        run: |
          java -jar revanced-cli.jar \
            patch -f \
            -p revanced-patches.jar \
              youtube.apk \
            -o youtube-revanced.apk
            
      # Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: "ReVanced YouTube Build - ${{ github.event.inputs.release_tag }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload APK to the Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: youtube-revanced.apk
          asset_name: youtube-revanced-${{ github.event.inputs.release_tag }}.apk
          asset_content_type: application/vnd.android.package-archive
