name: Patch YouTube ReVanced

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: "URL to download YouTube APK"
        required: true
        default: "https://eb5e7388c3df147b74dd2379b7cf8323.r2.cloudflarestorage.com/downloadprod/wp-content/uploads/2024/11/16/6746a64a31380/com.google.android.youtube_19.46.42-1549669824_minAPI26%28arm64-v8a%2Carmeabi-v7a%2Cx86%2Cx86_64%29%28nodpi%29_apkmirror.com.apk?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=72a5ba3a0b8a601e535d5525f12f8177%2F20241128%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20241128T034037Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Signature=61bb17f2ba3431374febb5efce2cc5f739558daa5e08008d120b51a8e9c43e98"
      release_tag:
        description: "Tag for the release (e.g., v1.0.0)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Download ReVanced CLI
      - name: Download ReVanced CLI
        run: |
          wget https://github.com/ReVanced/revanced-cli/releases/download/v5.0.0/revanced-cli-5.0.0-all.jar -O revanced-cli.jar

      # Download Patches and Integrations
      - name: Download Patches and Integrations
        run: |
          wget https://github.com/ReVanced/revanced-patches/releases/download/v5.2.0/patches-5.2.0.rvp -O revanced-patches.rvp
          wget https://github.com/ReVanced/revanced-integrations/releases/download/v1.17.0-dev.6/revanced-integrations-1.17.0-dev.6.apk -O integrations.apk

      # Download YouTube APK (from input)
      - name: Download YouTube APK
        run: |
          wget ${{ github.event.inputs.apk_url }} -O youtube.apk

      # Patch YouTube APK
      - name: Patch YouTube
        run: |
          java -jar revanced-cli.jar patch \
            --patches revanced-patches.rvp \
            -o youtube-revanced.apk \
            youtube.apk

      # Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: "ReVanced YouTube Build - ${{ github.event.inputs.release_tag }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload APK to the Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: youtube-revanced.apk
          asset_name: youtube-revanced-${{ github.event.inputs.release_tag }}.apk
          asset_content_type: application/vnd.android.package-archive
